# Generated by Django 4.2 on 2023-04-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.TextField(max_length=255)),
                ('valor', models.FloatField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
